// chat/theme.zig — Theme definitions for the Zig chat renderer
const std = @import("std");
const types = @import("types.zig");
const RGBA = types.RGBA;

pub const Theme = struct {
    id: []const u8,
    name: []const u8,
    background: RGBA,
    background_panel: RGBA,
    text: RGBA,
    text_muted: RGBA,
    text_dim: RGBA,
    primary: RGBA,
    accent: RGBA,
    success: RGBA,
    warning: RGBA,
    err: RGBA,
    border: RGBA,
    border_active: RGBA,
    channel_label: RGBA,
    timestamp: RGBA,
};

fn hexDigit(comptime c: u8) u8 {
    return switch (c) {
        '0'...'9' => c - '0',
        'a'...'f' => c - 'a' + 10,
        'A'...'F' => c - 'A' + 10,
        else => unreachable,
    };
}

fn hex(comptime s: []const u8) RGBA {
    @setEvalBranchQuota(10000);
    const r = comptime (hexDigit(s[1]) << 4) | hexDigit(s[2]);
    const g = comptime (hexDigit(s[3]) << 4) | hexDigit(s[4]);
    const b = comptime (hexDigit(s[5]) << 4) | hexDigit(s[6]);
    return .{
        @as(f32, @floatFromInt(r)) / 255.0,
        @as(f32, @floatFromInt(g)) / 255.0,
        @as(f32, @floatFromInt(b)) / 255.0,
        1.0,
    };
}

pub const themes = [_]Theme{
    .{
        .id = "one-dark",
        .name = "One Dark",
        .background = hex("#1a1a2e"),
        .background_panel = hex("#1a1a2e"),
        .text = hex("#abb2bf"),
        .text_muted = hex("#5c6370"),
        .text_dim = hex("#3e4452"),
        .primary = hex("#61afef"),
        .accent = hex("#c678dd"),
        .success = hex("#98c379"),
        .warning = hex("#e5c07b"),
        .err = hex("#e06c75"),
        .border = hex("#333333"),
        .border_active = hex("#61afef"),
        .channel_label = hex("#c678dd"),
        .timestamp = hex("#555555"),
    },
    .{
        .id = "nord",
        .name = "Nord",
        .background = hex("#2e3440"),
        .background_panel = hex("#2e3440"),
        .text = hex("#d8dee9"),
        .text_muted = hex("#4c566a"),
        .text_dim = hex("#3b4252"),
        .primary = hex("#88c0d0"),
        .accent = hex("#b48ead"),
        .success = hex("#a3be8c"),
        .warning = hex("#ebcb8b"),
        .err = hex("#bf616a"),
        .border = hex("#3b4252"),
        .border_active = hex("#88c0d0"),
        .channel_label = hex("#b48ead"),
        .timestamp = hex("#4c566a"),
    },
    .{
        .id = "catppuccin",
        .name = "Catppuccin",
        .background = hex("#1e1e2e"),
        .background_panel = hex("#1e1e2e"),
        .text = hex("#cdd6f4"),
        .text_muted = hex("#585b70"),
        .text_dim = hex("#313244"),
        .primary = hex("#89b4fa"),
        .accent = hex("#cba6f7"),
        .success = hex("#a6e3a1"),
        .warning = hex("#f9e2af"),
        .err = hex("#f38ba8"),
        .border = hex("#313244"),
        .border_active = hex("#89b4fa"),
        .channel_label = hex("#cba6f7"),
        .timestamp = hex("#585b70"),
    },
    .{
        .id = "gruvbox",
        .name = "Gruvbox",
        .background = hex("#282828"),
        .background_panel = hex("#282828"),
        .text = hex("#ebdbb2"),
        .text_muted = hex("#665c54"),
        .text_dim = hex("#3c3836"),
        .primary = hex("#83a598"),
        .accent = hex("#d3869b"),
        .success = hex("#b8bb26"),
        .warning = hex("#fabd2f"),
        .err = hex("#fb4934"),
        .border = hex("#3c3836"),
        .border_active = hex("#83a598"),
        .channel_label = hex("#d3869b"),
        .timestamp = hex("#665c54"),
    },
    .{
        .id = "matrix",
        .name = "Matrix",
        .background = hex("#000000"),
        .background_panel = hex("#000000"),
        .text = hex("#00ff41"),
        .text_muted = hex("#005500"),
        .text_dim = hex("#003300"),
        .primary = hex("#00ff41"),
        .accent = hex("#00ff41"),
        .success = hex("#00ff41"),
        .warning = hex("#00ff41"),
        .err = hex("#ff0000"),
        .border = hex("#003b00"),
        .border_active = hex("#00ff41"),
        .channel_label = hex("#00ff41"),
        .timestamp = hex("#005500"),
    },
    .{
        .id = "dracula",
        .name = "Dracula",
        .background = hex("#282a36"),
        .background_panel = hex("#282a36"),
        .text = hex("#f8f8f2"),
        .text_muted = hex("#6272a4"),
        .text_dim = hex("#44475a"),
        .primary = hex("#bd93f9"),
        .accent = hex("#ff79c6"),
        .success = hex("#50fa7b"),
        .warning = hex("#f1fa8c"),
        .err = hex("#ff5555"),
        .border = hex("#44475a"),
        .border_active = hex("#bd93f9"),
        .channel_label = hex("#ff79c6"),
        .timestamp = hex("#6272a4"),
    },
    .{
        .id = "solarized-dark",
        .name = "Solarized Dark",
        .background = hex("#002b36"),
        .background_panel = hex("#002b36"),
        .text = hex("#839496"),
        .text_muted = hex("#586e75"),
        .text_dim = hex("#073642"),
        .primary = hex("#268bd2"),
        .accent = hex("#d33682"),
        .success = hex("#859900"),
        .warning = hex("#b58900"),
        .err = hex("#dc322f"),
        .border = hex("#073642"),
        .border_active = hex("#268bd2"),
        .channel_label = hex("#d33682"),
        .timestamp = hex("#586e75"),
    },
    .{
        .id = "tokyo-night",
        .name = "Tokyo Night",
        .background = hex("#1a1b26"),
        .background_panel = hex("#1a1b26"),
        .text = hex("#a9b1d6"),
        .text_muted = hex("#565f89"),
        .text_dim = hex("#292e42"),
        .primary = hex("#7aa2f7"),
        .accent = hex("#bb9af7"),
        .success = hex("#9ece6a"),
        .warning = hex("#e0af68"),
        .err = hex("#f7768e"),
        .border = hex("#292e42"),
        .border_active = hex("#7aa2f7"),
        .channel_label = hex("#bb9af7"),
        .timestamp = hex("#565f89"),
    },
    .{
        .id = "monokai",
        .name = "Monokai",
        .background = hex("#272822"),
        .background_panel = hex("#272822"),
        .text = hex("#f8f8f2"),
        .text_muted = hex("#75715e"),
        .text_dim = hex("#3e3d32"),
        .primary = hex("#66d9ef"),
        .accent = hex("#f92672"),
        .success = hex("#a6e22e"),
        .warning = hex("#e6db74"),
        .err = hex("#f92672"),
        .border = hex("#3e3d32"),
        .border_active = hex("#66d9ef"),
        .channel_label = hex("#f92672"),
        .timestamp = hex("#75715e"),
    },
    .{
        .id = "rose-pine",
        .name = "Rose Pine",
        .background = hex("#191724"),
        .background_panel = hex("#191724"),
        .text = hex("#e0def4"),
        .text_muted = hex("#6e6a86"),
        .text_dim = hex("#26233a"),
        .primary = hex("#9ccfd8"),
        .accent = hex("#c4a7e7"),
        .success = hex("#31748f"),
        .warning = hex("#f6c177"),
        .err = hex("#eb6f92"),
        .border = hex("#26233a"),
        .border_active = hex("#9ccfd8"),
        .channel_label = hex("#c4a7e7"),
        .timestamp = hex("#6e6a86"),
    },
    .{
        .id = "everforest",
        .name = "Everforest",
        .background = hex("#2d353b"),
        .background_panel = hex("#2d353b"),
        .text = hex("#d3c6aa"),
        .text_muted = hex("#859289"),
        .text_dim = hex("#3d484d"),
        .primary = hex("#7fbbb3"),
        .accent = hex("#d699b6"),
        .success = hex("#a7c080"),
        .warning = hex("#dbbc7f"),
        .err = hex("#e67e80"),
        .border = hex("#3d484d"),
        .border_active = hex("#7fbbb3"),
        .channel_label = hex("#d699b6"),
        .timestamp = hex("#859289"),
    },
    .{
        .id = "kanagawa",
        .name = "Kanagawa",
        .background = hex("#1f1f28"),
        .background_panel = hex("#1f1f28"),
        .text = hex("#dcd7ba"),
        .text_muted = hex("#727169"),
        .text_dim = hex("#2a2a37"),
        .primary = hex("#7e9cd8"),
        .accent = hex("#957fb8"),
        .success = hex("#76946a"),
        .warning = hex("#e6c384"),
        .err = hex("#c34043"),
        .border = hex("#2a2a37"),
        .border_active = hex("#7e9cd8"),
        .channel_label = hex("#957fb8"),
        .timestamp = hex("#727169"),
    },
};

pub fn findTheme(id: []const u8) *const Theme {
    for (&themes) |*t| {
        if (std.mem.eql(u8, t.id, id)) return t;
    }
    return &themes[0]; // default to One Dark
}

pub fn getDefaultTheme() *const Theme {
    return &themes[0];
}
